// ============================================================
// HOTELS DATA — Disney World & Universal Orlando
// ============================================================

export const HOTELS = [

  // ══════════════════════════════════════════════════════════
  // DISNEY WORLD — DELUXE
  // ══════════════════════════════════════════════════════════
  {
    id: 'grand-floridian',
    name: 'Disney\'s Grand Floridian Resort & Spa',
    shortName: 'Grand Floridian',
    emoji: '🏰',
    resort: 'disney-world',
    tier: 'Deluxe',
    theme: 'Victorian seaside grandeur',
    accentColor: '#c8902a',
    priceRange: '$$$$$',
    location: 'Magic Kingdom Area',
    transportation: ['Monorail', 'Boat to Magic Kingdom', 'Disney Bus'],
    description: 'The crown jewel of Disney World resorts — a Victorian-era grand hotel on the shores of the Seven Seas Lagoon, just a monorail ride from Magic Kingdom. With its white architecture, red-gabled roofs, and a live orchestra in the lobby, it\'s the most iconic resort on property.',
    history: 'The Grand Floridian opened on June 28, 1988, designed to evoke the golden age of Florida resort travel in the late 1800s. Inspired by the historic seaside hotels of Victorian-era Florida — particularly the Hotel del Coronado in San Diego and the Tampa Bay Hotel — Imagineers created an atmosphere of refined elegance. Walt Disney himself never saw it, but the resort embodies his vision of a place where families could feel they were in a genuinely special destination.',
    trivia: [
      'The lobby features a live orchestra or band performing throughout the day — it\'s one of the only Disney resorts with live music as a permanent fixture',
      'The main building\'s lobby chandelier contains over 11,000 hand-blown glass pieces',
      'The resort connects directly to Magic Kingdom via the resort monorail — the only resort with this direct connection alongside the Polynesian and Contemporary',
      'Victoria & Albert\'s, the hotel\'s signature restaurant, is one of the only AAA Five Diamond restaurants in Florida and requires a jacket for men',
      'The Mary Poppins suite on the fourth floor was used to house VIP guests including visiting heads of state',
      'In 2021, a Disney Vacation Club tower addition opened adjacent to the original building',
      'The beach has a direct view of the Magic Kingdom fireworks — some of the best on property without park admission',
    ],
    proTips: [
      '🎆 Book the beach chairs for a fireworks view — you can watch Happily Ever After from the Grand Floridian beach without park admission',
      '🚝 The monorail to Magic Kingdom runs until midnight — you can leave the park and be back in your room in under 10 minutes',
      '🍽️ Narcoossee\'s has waterfront seating with a Magic Kingdom castle view — prime during fireworks',
      '🎹 The lobby orchestra performs multiple sets daily — check the schedule at the front desk',
      '🛏️ Garden Wing rooms are significantly cheaper with nearly identical amenities to the main building',
    ],
    specs: {
      opened: '1988',
      rooms: '867 rooms + suites',
      pools: '2 pools (including a zero-entry feature pool)',
      restaurants: '7 dining locations',
      transportation: 'Monorail + Boat + Bus',
      tier: 'Deluxe Resort',
    },
    resources: [
      { label: '🏰 Book Grand Floridian', url: 'https://disneyworld.disney.go.com/resorts/grand-floridian-resort-and-spa/' },
    ],
  },

  {
    id: 'polynesian-village',
    name: 'Disney\'s Polynesian Village Resort',
    shortName: 'Polynesian Village',
    emoji: '🌺',
    resort: 'disney-world',
    tier: 'Deluxe',
    theme: 'South Seas Polynesian paradise',
    accentColor: '#16a34a',
    priceRange: '$$$$$',
    location: 'Magic Kingdom Area',
    transportation: ['Monorail', 'Boat to Magic Kingdom', 'Disney Bus'],
    description: 'A lush, tropical Polynesian-themed resort on the Seven Seas Lagoon with an atmosphere that transports guests to Hawaii and the South Pacific. Famous for its tiki torches, tropical gardens, and stunning view of Cinderella Castle across the water.',
    history: 'The Polynesian was one of the two original Disney World hotels that opened on October 1, 1971 — the same day as Magic Kingdom. Walt Disney himself helped plan the resort, inspired by his love of the South Pacific. The original "longhouses" were built in Polynesian architectural style. In 2015, a Disney Vacation Club expansion added bungalows built over the Seven Seas Lagoon — the first overwater bungalows at any Disney resort.',
    trivia: [
      'One of the original opening-day Disney World hotels — it opened on October 1, 1971 alongside Magic Kingdom',
      'The overwater bungalows (added in 2015) are among the most expensive accommodations in all of Disney World — and one of the most unique anywhere',
      'Kona Café\'s Tonga Toast — a battered strawberry cream-stuffed French toast — has been on the menu for decades and has its own cult following',
      'The 1971 space-themed monorail decorated with tropical colors can be seen throughout the resort',
      'Disney\'s Spirit of Aloha dinner show has been performed at the Polynesian since 1976, making it one of the longest-running dinner shows in Disney history',
      'The Great Ceremonial House lobby features 80-foot tall Royal Palms and a cascading waterfall',
      'A Hidden Mickey can be found in the flower arrangements in the lobby — it changes seasonally',
    ],
    proTips: [
      '🌅 The beach at the Polynesian has the best direct view of the Magic Kingdom castle and fireworks on property',
      '🍹 The Pineapple Lanai serves Dole Whip — get it from the resort to skip Magic Kingdom lines',
      '🛶 Rent a boat from the marina for a private lagoon cruise',
      '🏄 The Samoa pool is quieter than the main volcano pool — better for kids',
      '⛴️ Take the boat to Magic Kingdom for a scenic 10-minute alternative to the monorail',
    ],
    specs: {
      opened: '1971',
      rooms: '847 rooms + bungalows',
      pools: '2 pools (including volcano feature pool)',
      restaurants: '5 dining locations',
      transportation: 'Monorail + Boat + Bus',
      tier: 'Deluxe Resort',
    },
    resources: [
      { label: '🌺 Book Polynesian Village', url: 'https://disneyworld.disney.go.com/resorts/polynesian-village-resort/' },
    ],
  },

  {
    id: 'contemporary',
    name: 'Disney\'s Contemporary Resort',
    shortName: 'Contemporary',
    emoji: '🔷',
    resort: 'disney-world',
    tier: 'Deluxe',
    theme: 'Modernist futurism',
    accentColor: '#0ea5e9',
    priceRange: '$$$$$',
    location: 'Magic Kingdom Area',
    transportation: ['Monorail through the building', 'Walk to Magic Kingdom', 'Disney Bus'],
    description: 'An architectural icon — the monorail literally passes through the middle of the A-frame tower. Bold, modern, and just a 10-minute walk from Magic Kingdom, the Contemporary is one of the most recognizable buildings at Walt Disney World.',
    history: 'The Contemporary was one of two original hotels to open with Magic Kingdom on October 1, 1971. It was revolutionary — the first hotel in the world with an internal monorail system. The building was constructed using prefabricated room modules that were slid into the A-frame structure like drawers. The massive "Mary Blair mural" — a 90-foot, five-story ceramic tile artwork — was installed by the legendary Disney artist.',
    trivia: [
      'The resort was prefabricated — guest room modules were built offsite and slid into the A-frame structure by crane',
      'The monorail passes through the Grand Canyon Concourse on the fourth floor — guests can wave to riders',
      'Mary Blair\'s 90-foot ceramic tile mural on the Grand Canyon Concourse is one of the largest single artworks at Walt Disney World',
      'Bay Lake Tower, the DVC expansion, connects directly to the Contemporary via a covered walkway',
      'Chef Mickey\'s on the Grand Canyon Concourse has been a character dining location since 1971',
      'The rooftop of the Contemporary offers one of the best views of Magic Kingdom fireworks — accessible from California Grill',
      'Walt Disney himself stayed in Suite 4E6 during opening week of Magic Kingdom in 1971',
    ],
    proTips: [
      '🚶 Walk to Magic Kingdom in 10 minutes — the fastest transit option on property',
      '🍽️ California Grill on the 15th floor has rooftop fireworks viewing — reserve months in advance',
      '🚝 Watch the monorail from the Grand Canyon Concourse level — it\'s a unique experience',
      '👀 Request a Magic Kingdom-view tower room for the best castle views on property',
    ],
    specs: {
      opened: '1971',
      rooms: '655 rooms + suites',
      pools: '1 main pool + Bay Lake Tower pool',
      restaurants: '4 dining locations',
      transportation: 'Monorail (through building) + Walk + Bus',
      tier: 'Deluxe Resort',
    },
    resources: [
      { label: '🔷 Book Contemporary', url: 'https://disneyworld.disney.go.com/resorts/contemporary-resort/' },
    ],
  },

  {
    id: 'wilderness-lodge',
    name: 'Disney\'s Wilderness Lodge',
    shortName: 'Wilderness Lodge',
    emoji: '🌲',
    resort: 'disney-world',
    tier: 'Deluxe',
    theme: 'Pacific Northwest national park lodge',
    accentColor: '#92400e',
    priceRange: '$$$$',
    location: 'Magic Kingdom Area',
    transportation: ['Boat to Magic Kingdom', 'Disney Bus'],
    description: 'A breathtaking recreation of the great National Park lodges of the American West — think Old Faithful Inn at Yellowstone. An 82-foot stone fireplace dominates the lobby, a geyser erupts hourly outside, and the towering pines create an atmosphere unlike anywhere else on Disney property.',
    history: 'Wilderness Lodge opened on May 28, 1994, designed to replicate the grand lodges built by the National Park Service in the late 1800s and early 1900s. The resort uses genuine Pacific Northwest architectural details including Indigenous American artistic motifs. The geyser outside erupts at the same intervals as a real geyser.',
    trivia: [
      'The geyser outside the resort erupts on a schedule matching real geysers — most prominently at sunrise',
      'The 82-foot fireplace in the lobby uses six different types of genuine rock samples from the American West, representing geological strata',
      'Artist Point\'s signature dish — the Bear Tracks brownie sundae — has been on the menu since opening day in 1994',
      'The resort\'s creek runs from a "hot spring" inside the lobby all the way to Bay Lake — it\'s a flowing body of water',
      'Disney Vacation Club Copper Creek Villas expanded the resort in 2017 with cabin-style accommodations on the water',
    ],
    proTips: [
      '⛴️ The boat to Magic Kingdom offers a scenic 20-minute ride through Bay Lake — one of the most pleasant transits on property',
      '🌄 Sunrise at the resort with the geyser eruption is genuinely spectacular and crowd-free',
      '🍻 Territory Lounge serves craft cocktails with a great fireplace ambiance',
    ],
    specs: {
      opened: '1994',
      rooms: '727 rooms + cabins',
      pools: '2 pools (including Silver Creek Springs)',
      restaurants: '4 dining locations',
      transportation: 'Boat + Bus',
      tier: 'Deluxe Resort',
    },
    resources: [
      { label: '🌲 Book Wilderness Lodge', url: 'https://disneyworld.disney.go.com/resorts/wilderness-lodge-resort/' },
    ],
  },

  {
    id: 'beach-club',
    name: 'Disney\'s Beach Club Resort',
    shortName: 'Beach Club',
    emoji: '⛱️',
    resort: 'disney-world',
    tier: 'Deluxe',
    theme: 'New England seaside beach club',
    accentColor: '#0891b2',
    priceRange: '$$$$',
    location: 'EPCOT Area',
    transportation: ['Walk to EPCOT', 'Walk to Hollywood Studios (20 min)', 'Boat to Hollywood Studios', 'Disney Bus'],
    description: 'A pastel-blue New England beach resort with the legendary Stormalong Bay — the most acclaimed pool complex at any Disney resort — and walking distance to EPCOT\'s back gate. If you\'re spending time at EPCOT, this is the premier choice.',
    history: 'Beach Club opened on November 19, 1990, designed as a companion to the Yacht Club next door. Both were designed by architect Robert A.M. Stern to evoke the grand resort hotels of Cape Cod and Newport, Rhode Island in the late 1800s.',
    trivia: [
      'Stormalong Bay — the shared pool complex with Yacht Club — is widely considered the best resort pool at Walt Disney World. It features a lazy river, a shipwreck slide, sand-bottom sections, and multiple water features',
      'The pool\'s lazy river is 750 feet long — the longest at any Disney resort',
      'Cape May Café\'s breakfast character buffet is one of the most relaxed character dining experiences at Disney World',
      'The back gate of EPCOT is a 5-minute walk — you can walk to the park without a bus or boat',
      'The Beaches & Cream Soda Shop is famous for the "Kitchen Sink" — a massive sundae served in an actual kitchen sink',
    ],
    proTips: [
      '🚶 Walk to EPCOT\'s International Gateway in 5 minutes — the best perk of this resort',
      '🏊 Stormalong Bay is adults-friendly in the morning before crowds arrive — genuinely worth the resort tier',
      '🍦 Order the Kitchen Sink at Beaches & Cream — it\'s a rite of passage',
      '⛵ Boat service to Hollywood Studios is a scenic alternative to walking',
    ],
    specs: {
      opened: '1990',
      rooms: '583 rooms',
      pools: 'Stormalong Bay (shared with Yacht Club) + quiet pool',
      restaurants: '4 dining locations',
      transportation: 'Walk to EPCOT + Boat + Bus',
      tier: 'Deluxe Resort',
    },
    resources: [
      { label: '⛱️ Book Beach Club', url: 'https://disneyworld.disney.go.com/resorts/beach-club-resort/' },
    ],
  },

  {
    id: 'yacht-club',
    name: 'Disney\'s Yacht Club Resort',
    shortName: 'Yacht Club',
    emoji: '⚓',
    resort: 'disney-world',
    tier: 'Deluxe',
    theme: 'New England yacht club elegance',
    accentColor: '#1e3a5f',
    priceRange: '$$$$',
    location: 'EPCOT Area',
    transportation: ['Walk to EPCOT', 'Walk to Hollywood Studios (20 min)', 'Boat to Hollywood Studios', 'Disney Bus'],
    description: 'The more formal sibling of Beach Club — darker navy and silver tones, a nautical aesthetic, and the same access to Stormalong Bay and EPCOT\'s back gate. Yachtsman Steakhouse is one of the finest restaurants on Disney property.',
    history: 'Yacht Club opened October 5, 1990, just weeks before Beach Club. The two resorts share the same pool complex and general infrastructure. The Yacht Club leans slightly more formal — dark hardwood, navy colors, and a traditional New England yachting aesthetic.',
    trivia: [
      'Shares the legendary Stormalong Bay pool complex with Beach Club next door',
      'Yachtsman Steakhouse serves USDA Prime beef dry-aged on-site — one of the top steakhouses on Disney property',
      'The Yacht Club and Beach Club are connected internally — guests can walk through both lobbies',
      'The resort\'s lighthouse at the entrance is fully functional and visible across Crescent Lake',
    ],
    proTips: [
      '🥩 Yachtsman Steakhouse is one of Disney\'s best restaurants — reserve 60 days in advance',
      '🚶 Same EPCOT walking access as Beach Club — the top reason to stay in this area',
      '⚓ The Crew\'s Cup Lounge is an underrated bar for light bites and drinks',
    ],
    specs: {
      opened: '1990',
      rooms: '630 rooms',
      pools: 'Stormalong Bay (shared with Beach Club)',
      restaurants: '4 dining locations',
      transportation: 'Walk to EPCOT + Boat + Bus',
      tier: 'Deluxe Resort',
    },
    resources: [
      { label: '⚓ Book Yacht Club', url: 'https://disneyworld.disney.go.com/resorts/yacht-club-resort/' },
    ],
  },

  {
    id: 'animal-kingdom-lodge',
    name: 'Disney\'s Animal Kingdom Lodge',
    shortName: 'Animal Kingdom Lodge',
    emoji: '🦒',
    resort: 'disney-world',
    tier: 'Deluxe',
    theme: 'African savanna lodge',
    accentColor: '#92400e',
    priceRange: '$$$$',
    location: 'Animal Kingdom Area',
    transportation: ['Disney Bus'],
    description: 'One of the most immersive resort experiences anywhere in the world — over 30 species of African wildlife roam freely on the savannas surrounding the resort. Wake up to giraffes outside your window. The architecture is modeled on the grand lodge of the Arusha, Tanzania area.',
    history: 'Animal Kingdom Lodge opened April 16, 2001. Disney spent years working with African cultural experts, architects, and animal specialists to create an authentic environment. The lobby features genuine African artifacts collected by Disney Imagineers during research trips across the continent. Over 200 authentic African artifacts are displayed throughout the resort.',
    trivia: [
      'More than 30 species of African animals live on the resort\'s four savanna viewing areas — you can see them from your room balcony, the lobby, or designated viewing areas',
      'The lobby "Arusha" rock structure weighs over 500,000 pounds and was constructed by authentic African craftspeople',
      'More than 200 genuine African artifacts are displayed throughout the resort — not reproductions',
      'Boma — Flavors of Africa serves one of the largest breakfast buffets at Disney World featuring authentic African dishes',
      'Jiko — The Cooking Place has won awards for its South African wine program — one of the best in Florida',
      'The Cultural Representative Program employs cast members from various African nations who serve as cultural guides and share personal stories',
      'Flamingos, zebras, giraffes, and wildebeest are among the species you might see from savanna-view rooms',
    ],
    proTips: [
      '🦒 Book a savanna-view room — the premium is absolutely worth it for waking up to giraffes',
      '🌙 The Sunset Savanna viewing area has fire pits and African appetizers at sunset — a genuine highlight',
      '📱 Check the Disney app for savanna ranger talks — free and fascinating',
      '🍽️ Jiko is a bucket-list meal — the bobotie and South African wines are remarkable',
      '🌅 Giraffes are most active at dawn and dusk — watch from your balcony at sunrise',
    ],
    specs: {
      opened: '2001',
      rooms: '972 rooms',
      savannas: '4 private savannas with 30+ species',
      pools: '2 pools',
      restaurants: '5 dining locations',
      transportation: 'Bus only (furthest from Magic Kingdom area)',
      tier: 'Deluxe Resort',
    },
    resources: [
      { label: '🦒 Book Animal Kingdom Lodge', url: 'https://disneyworld.disney.go.com/resorts/animal-kingdom-lodge/' },
    ],
  },

  {
    id: 'boardwalk-inn',
    name: 'Disney\'s BoardWalk Inn',
    shortName: 'BoardWalk Inn',
    emoji: '🎡',
    resort: 'disney-world',
    tier: 'Deluxe',
    theme: 'Atlantic City boardwalk circa 1930s',
    accentColor: '#7c3aed',
    priceRange: '$$$$',
    location: 'EPCOT Area',
    transportation: ['Walk to EPCOT', 'Walk or Boat to Hollywood Studios', 'Disney Bus'],
    description: 'A vibrant boardwalk along Crescent Lake with street performers, outdoor dining, a dueling piano bar, and a sports bar. Walk to EPCOT\'s back gate or Hollywood Studios. Lively at night in a way unlike any other Disney resort.',
    history: 'Disney\'s BoardWalk Inn & Villas opened June 26, 1996, themed to the boardwalks of Atlantic City and Coney Island in their golden era — approximately 1900–1940. Entertainment on the actual boardwalk includes street performers, carnival games, and live music.',
    trivia: [
      'Jellyrolls, the dueling piano bar, has been performing since 1996 — one of the best live music experiences at Disney World (21+ only)',
      'ESPN Club broadcasts live sports and is an official sports broadcast partner',
      'The carriage ride clock atop the main building chimes hourly with Disney music',
      'The BoardWalk is a public promenade — any Disney guest can walk it without staying at the resort',
    ],
    proTips: [
      '🎹 Jellyrolls is a must-do evening activity — request songs from the dueling pianists',
      '🚶 EPCOT walking access is the same as Beach Club and Yacht Club',
      '🌙 The boardwalk itself is most atmospheric at night with the lights and entertainment',
    ],
    specs: {
      opened: '1996',
      rooms: '378 rooms',
      pools: '2 pools (including Luna Park with 200-foot slide)',
      restaurants: '5+ dining and entertainment venues',
      transportation: 'Walk to EPCOT + Walk/Boat to HS + Bus',
      tier: 'Deluxe Resort',
    },
    resources: [
      { label: '🎡 Book BoardWalk Inn', url: 'https://disneyworld.disney.go.com/resorts/boardwalk-inn/' },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // DISNEY WORLD — MODERATE
  // ══════════════════════════════════════════════════════════
  {
    id: 'coronado-springs',
    name: 'Disney\'s Coronado Springs Resort',
    shortName: 'Coronado Springs',
    emoji: '🌵',
    resort: 'disney-world',
    tier: 'Moderate',
    theme: 'Spanish colonial Mexico and American Southwest',
    accentColor: '#d97706',
    priceRange: '$$$',
    location: 'Animal Kingdom Area',
    transportation: ['Disney Bus'],
    description: 'A sprawling Spanish colonial resort centered on the Lago Dorado lagoon, with the Gran Destino Tower offering some of the best room views on all of Disney property. The most conference-friendly resort at Walt Disney World, blending business amenities with Disney magic.',
    history: 'Coronado Springs opened August 1, 1997. The Gran Destino Tower, a luxury addition, opened in 2019, adding skyline views and elevated dining. The resort is named for Francisco Vázquez de Coronado, the Spanish conquistador who explored the American Southwest in the 1540s.',
    trivia: [
      'Gran Destino Tower has rooms with floor-to-ceiling windows overlooking the lagoon — among the most stunning views of any Disney resort room',
      'The Dig Site pool area features a Mayan pyramid with a waterslide',
      'Toledo — Tapas, Steak & Seafood on the 16th floor of Gran Destino Tower is one of Disney\'s finest dining experiences',
      'The resort has the largest convention center on Disney property — it hosts major conferences year-round',
    ],
    proTips: [
      '🏨 Book Gran Destino Tower rooms for remarkable views and a more elevated experience',
      '🌅 The rooftop lounge at Gran Destino Tower is open in the evenings with skyline views',
      '🎊 The convention schedule affects crowd levels — check before booking',
    ],
    specs: {
      opened: '1997',
      rooms: '1,921 rooms (including Gran Destino)',
      pools: '2 pools including Dig Site pyramid pool',
      restaurants: '5 dining locations',
      transportation: 'Bus only',
      tier: 'Moderate Resort',
    },
    resources: [
      { label: '🌵 Book Coronado Springs', url: 'https://disneyworld.disney.go.com/resorts/coronado-springs-resort/' },
    ],
  },

  {
    id: 'caribbean-beach',
    name: 'Disney\'s Caribbean Beach Resort',
    shortName: 'Caribbean Beach',
    emoji: '🏝️',
    resort: 'disney-world',
    tier: 'Moderate',
    theme: 'Caribbean island villages',
    accentColor: '#0891b2',
    priceRange: '$$$',
    location: 'EPCOT Area',
    transportation: ['Disney Skyliner to EPCOT and Hollywood Studios', 'Disney Bus'],
    description: 'Six colorful Caribbean island-themed villages surrounding a central lake, with the added bonus of Disney Skyliner gondola service to EPCOT and Hollywood Studios. The best transportation value among moderate resorts.',
    history: 'Caribbean Beach opened October 1, 1988 as Disney World\'s first moderate-priced resort. In 2019, the Disney Skyliner gondola system launched with Caribbean Beach as a major hub, transforming its transportation access overnight.',
    trivia: [
      'Caribbean Beach is a primary hub of the Disney Skyliner — gondola service to EPCOT\'s International Gateway and Hollywood Studios',
      'The resort\'s six "villages" are each themed to a different Caribbean island: Aruba, Barbados, Jamaica, Martinique, Trinidad, and Tobago',
      'Sebastian\'s Bistro serves Caribbean-inspired cuisine with live musical entertainment',
      'Old Port Royale, the central marketplace, is themed as a Spanish colonial port town',
    ],
    proTips: [
      '🚡 The Skyliner to EPCOT and Hollywood Studios is a genuine delight — scenic and efficient',
      '🌴 Walk around the lake at sunset — genuinely beautiful for a moderate resort',
      '🍹 Sebastian\'s Bistro is underrated — one of the better moderate resort restaurants',
    ],
    specs: {
      opened: '1988',
      rooms: '2,112 rooms',
      pools: '1 main pool + 6 quiet pools',
      restaurants: '2 table service + multiple quick service',
      transportation: 'Disney Skyliner + Bus',
      tier: 'Moderate Resort',
    },
    resources: [
      { label: '🏝️ Book Caribbean Beach', url: 'https://disneyworld.disney.go.com/resorts/caribbean-beach-resort/' },
    ],
  },

  {
    id: 'port-orleans-riverside',
    name: 'Disney\'s Port Orleans Resort — Riverside',
    shortName: 'Port Orleans Riverside',
    emoji: '🎷',
    resort: 'disney-world',
    tier: 'Moderate',
    theme: 'Antebellum Louisiana plantation',
    accentColor: '#065f46',
    priceRange: '$$$',
    location: 'Disney Springs Area',
    transportation: ['Boat to Disney Springs', 'Disney Bus'],
    description: 'A sprawling, beautiful resort themed to the plantation-era American South — moss-covered oaks, winding rivers, and a gorgeous landscape. The Royal Guest Rooms themed to Disney royalty are among the most charming moderate rooms on property.',
    history: 'Port Orleans Riverside opened February 2, 1992 as "Dixie Landings." The Royal Guest Rooms were added in 2012, featuring princess-themed décor with rope lighting and character touches.',
    trivia: [
      'The Royal Guest Rooms are themed to Disney princesses — headboards light up with firefly effects and Tinker Bell visits at night via a light effect on the ceiling',
      'Riverside Mill is one of the most charming food courts on Disney property, set in a working watermill',
      'Boat service to Disney Springs runs seasonally — a leisurely way to reach shopping and dining',
      'The grounds are among the most beautiful at any Disney resort — the oak trees are genuine old-growth',
    ],
    proTips: [
      '👸 Book a Royal Guest Room if traveling with young children — the details delight kids',
      '⛵ Take the boat to Disney Springs rather than the bus when available — scenic and relaxing',
      '🌳 Walk the grounds at dusk — the river and landscaping are genuinely lovely',
    ],
    specs: {
      opened: '1992',
      rooms: '2,048 rooms',
      pools: '2 pools',
      restaurants: '2 dining locations',
      transportation: 'Boat to Disney Springs + Bus',
      tier: 'Moderate Resort',
    },
    resources: [
      { label: '🎷 Book Port Orleans Riverside', url: 'https://disneyworld.disney.go.com/resorts/port-orleans-resort-riverside/' },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // DISNEY WORLD — VALUE
  // ══════════════════════════════════════════════════════════
  {
    id: 'art-of-animation',
    name: 'Disney\'s Art of Animation Resort',
    shortName: 'Art of Animation',
    emoji: '🎨',
    resort: 'disney-world',
    tier: 'Value',
    theme: 'Disney/Pixar animated film celebration',
    accentColor: '#7c3aed',
    priceRange: '$$',
    location: 'EPCOT Area (via Skyliner)',
    transportation: ['Disney Skyliner to EPCOT/Hollywood Studios', 'Disney Bus'],
    description: 'The most visually spectacular value resort at Disney World — larger-than-life sculptures of characters from Finding Nemo, Cars, The Lion King, and The Little Mermaid surround the resort. The family suites sleep up to six guests, making this the best value for larger families.',
    history: 'Art of Animation opened in phases in 2012 as a companion to Pop Century across Hourglass Lake. The two resorts share the Disney Skyliner station. Unlike other value resorts, Art of Animation emphasizes the actual art of Disney animation — concept art, production sketches, and character development is displayed throughout.',
    trivia: [
      'The Cars section has life-size reproductions of Radiator Springs, including Flo\'s V8 Café and Ramone\'s House of Body Art',
      'The Big Blue Pool (Finding Nemo section) is the largest pool at any Disney resort',
      'Family suites sleep up to 6 guests and include a full kitchenette — a remarkable value compared to booking two rooms',
      'The Disney Skyliner connects to EPCOT and Hollywood Studios — an upgrade over most value resorts',
      'Concept art and production drawings from actual Disney animated films line the hallways',
    ],
    proTips: [
      '🚡 The Skyliner access makes this the best-connected value resort on property',
      '👨‍👩‍👧‍👦 Family suites are the best value per person for groups of 5–6',
      '🐠 The Big Blue Pool is genuinely fun — Nemo theming is immersive even in the water',
      '🎨 Walk the entire resort to see all the concept art displays — genuinely fascinating',
    ],
    specs: {
      opened: '2012',
      rooms: '1,984 rooms + 1,120 family suites',
      pools: '3 pools including Big Blue (largest on property)',
      restaurants: '2 dining locations',
      transportation: 'Disney Skyliner + Bus',
      tier: 'Value Resort',
    },
    resources: [
      { label: '🎨 Book Art of Animation', url: 'https://disneyworld.disney.go.com/resorts/art-of-animation-resort/' },
    ],
  },

  {
    id: 'pop-century',
    name: 'Disney\'s Pop Century Resort',
    shortName: 'Pop Century',
    emoji: '🎸',
    resort: 'disney-world',
    tier: 'Value',
    theme: 'American pop culture by decade (1950s–1990s)',
    accentColor: '#dc2626',
    priceRange: '$$',
    location: 'EPCOT Area (via Skyliner)',
    transportation: ['Disney Skyliner to EPCOT/Hollywood Studios', 'Disney Bus'],
    description: 'A celebration of American pop culture decade by decade — giant yo-yos, foosball players, Big Wheels, and Rubik\'s Cubes tower over the buildings. Disney Skyliner access makes it the most well-connected value resort for EPCOT and Hollywood Studios visitors.',
    history: 'Pop Century opened December 14, 2003. Giant icons from each decade of American pop culture (1950s–1990s) are the defining feature. The resort shares Hourglass Lake with Art of Animation.',
    trivia: [
      'The giant foosball players in the 1970s section are 35 feet tall',
      'The Skyliner station connects Pop Century to Art of Animation, EPCOT, and Hollywood Studios',
      'Everything Pop Shopping & Dining is one of the largest value resort food courts on property',
      'The 1990s section features a giant laptop computer and cell phone from the era',
    ],
    proTips: [
      '🚡 The Skyliner is the #1 reason to choose Pop Century — fast access to EPCOT and Hollywood Studios',
      '🏊 The Hippy Dippy Pool is the main pool and one of the more atmospheric value resort pools',
      '🎭 Worth walking to Art of Animation just to see the Cars and Nemo sections even if you\'re not staying there',
    ],
    specs: {
      opened: '2003',
      rooms: '2,880 rooms',
      pools: '3 pools',
      restaurants: '1 dining location (large food court)',
      transportation: 'Disney Skyliner + Bus',
      tier: 'Value Resort',
    },
    resources: [
      { label: '🎸 Book Pop Century', url: 'https://disneyworld.disney.go.com/resorts/pop-century-resort/' },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // UNIVERSAL ORLANDO
  // ══════════════════════════════════════════════════════════
  {
    id: 'hard-rock-hotel',
    name: 'Hard Rock Hotel at Universal Orlando',
    shortName: 'Hard Rock Hotel',
    emoji: '🎸',
    resort: 'universal-orlando',
    tier: 'Premier',
    theme: 'Rock and roll music hotel',
    accentColor: '#dc2626',
    priceRange: '$$$$',
    location: 'On-site Universal (walking distance)',
    transportation: ['Walk to Universal Studios Florida', 'Walk to Islands of Adventure', 'Water taxi'],
    description: 'The flagship on-site Universal hotel — iconic pink exterior, rock memorabilia throughout, and the most coveted perk in all of Universal Orlando: complimentary Early Park Admission and Universal Express Unlimited access for all guests.',
    history: 'Hard Rock Hotel opened January 25, 1999 as part of Universal\'s first wave of on-site hotels. Designed to feel like a rock star is staying at a private mansion, the hotel features an extensive collection of music memorabilia. The pool has an underwater sound system.',
    trivia: [
      'Hotel guests receive Universal Express Unlimited — allowing them to skip the regular line on most attractions as many times as they want, every day',
      'The pool has a genuine underwater music system — you can hear rock music while swimming below the surface',
      'Over 2,000 pieces of genuine rock music memorabilia are displayed throughout the hotel',
      'The hotel is within a 5-minute walk of both Universal Studios Florida and Islands of Adventure entrances',
      'Early Park Admission (1 hour before general public) is included for all on-site Universal hotel guests',
      'The suite where rock stars and celebrities stay features a private pool, recording studio, and multiple bedrooms',
    ],
    proTips: [
      '⚡ Universal Express Unlimited is the single most valuable perk at Universal — it typically costs $100+/person/day to purchase separately',
      '🚶 Walking distance to both parks and Epic Universe via shuttle — no transportation waits',
      '🎵 The pool is open until midnight — the live music on weekends is a genuine party',
      '⏰ Early Park Admission means riding VelociCoaster before crowds arrive — a huge strategic advantage',
    ],
    specs: {
      opened: '1999',
      rooms: '650 rooms + suites',
      pools: '1 main pool with underwater sound system',
      restaurants: '4 dining locations including The Palm steakhouse',
      transportation: 'Walk + Water taxi',
      tier: 'Premier On-Site Hotel',
      keyPerk: 'Universal Express Unlimited + Early Park Admission',
    },
    resources: [
      { label: '🎸 Book Hard Rock Hotel', url: 'https://www.universalorlando.com/web/en/us/hotels/hard-rock-hotel' },
    ],
  },

  {
    id: 'portofino-bay',
    name: 'Loews Portofino Bay Hotel at Universal Orlando',
    shortName: 'Portofino Bay',
    emoji: '🇮🇹',
    resort: 'universal-orlando',
    tier: 'Premier',
    theme: 'Italian Riviera fishing village',
    accentColor: '#0891b2',
    priceRange: '$$$$',
    location: 'On-site Universal',
    transportation: ['Water taxi to parks', 'Walk to parks (15 min)', 'Shuttle'],
    description: 'The most romantic hotel at Universal Orlando — a meticulous recreation of the seaside Italian village of Portofino, with a central harbor, piazzas, and gelato shops. Premier perks include Universal Express Unlimited and Early Park Admission.',
    history: 'Portofino Bay opened September 2, 1999. Imagineers studied the actual village of Portofino, Italy extensively and recreated its signature pastel buildings, cobblestone streets, and harbor atmosphere at 2/3 scale.',
    trivia: [
      'The harbor is built at 2/3 the actual scale of the real Portofino harbor in Italy',
      'The hotel was designed with such attention to detail that travel writers have called it the most convincing European recreation in Florida',
      'Mandara Spa is considered one of the finest resort spas in central Florida',
      'Universal Express Unlimited is included for all guests — the same powerful perk as Hard Rock',
    ],
    proTips: [
      '🇮🇹 The harbor piazza is beautiful at night — have dinner at Trattoria del Porto',
      '⚡ Universal Express Unlimited makes this a highly efficient park experience',
      '🛥️ The water taxi to the parks is a scenic 15-minute ride',
    ],
    specs: {
      opened: '1999',
      rooms: '750 rooms',
      pools: '3 pools',
      restaurants: '5 dining locations',
      transportation: 'Water taxi + Shuttle + Walk',
      tier: 'Premier On-Site Hotel',
      keyPerk: 'Universal Express Unlimited + Early Park Admission',
    },
    resources: [
      { label: '🇮🇹 Book Portofino Bay', url: 'https://www.universalorlando.com/web/en/us/hotels/loews-portofino-bay-hotel' },
    ],
  },

  {
    id: 'royal-pacific',
    name: 'Loews Royal Pacific Resort at Universal Orlando',
    shortName: 'Royal Pacific',
    emoji: '🌴',
    resort: 'universal-orlando',
    tier: 'Premier',
    theme: '1950s South Pacific island resort',
    accentColor: '#065f46',
    priceRange: '$$$',
    location: 'On-site Universal',
    transportation: ['Walk to parks (10 min)', 'Water taxi', 'Shuttle'],
    description: 'The most affordable of Universal\'s Premier hotels — same Universal Express Unlimited perk at a lower price point. South Seas island theme with a large lagoon pool and lush tropical gardens.',
    history: 'Royal Pacific Resort opened July 26, 2002. The resort is themed to a 1950s South Pacific luxury resort, inspired by the exotic island destinations that became popular travel destinations after World War II.',
    trivia: [
      'Offers the same Universal Express Unlimited perk as Hard Rock and Portofino Bay at a significantly lower nightly rate',
      'The lagoon pool has a sand beach section and water slide',
      'Jake\'s American Bar has been a casual gathering spot for park guests since opening',
      'Island-style entertainment including fire performers and luau-themed events are held regularly',
    ],
    proTips: [
      '💰 Best value among Premier hotels — same Express Unlimited at a lower cost than Hard Rock or Portofino',
      '⚡ Universal Express Unlimited is the key perk — if you\'re doing Universal for multiple days, it pays for itself',
      '🛥️ The water taxi is a more pleasant transit option than the shuttle',
    ],
    specs: {
      opened: '2002',
      rooms: '1,000 rooms',
      pools: '1 lagoon pool with sand beach',
      restaurants: '3 dining locations',
      transportation: 'Walk + Water taxi + Shuttle',
      tier: 'Premier On-Site Hotel',
      keyPerk: 'Universal Express Unlimited + Early Park Admission',
    },
    resources: [
      { label: '🌴 Book Royal Pacific', url: 'https://www.universalorlando.com/web/en/us/hotels/loews-royal-pacific-resort' },
    ],
  },

  {
    id: 'sapphire-falls',
    name: 'Loews Sapphire Falls Resort at Universal Orlando',
    shortName: 'Sapphire Falls',
    emoji: '💧',
    resort: 'universal-orlando',
    tier: 'Preferred',
    theme: 'Caribbean waterfall resort',
    accentColor: '#0284c7',
    priceRange: '$$$',
    location: 'On-site Universal',
    transportation: ['Shuttle to parks (10 min)', 'Water taxi'],
    description: 'A Caribbean-themed resort with a central waterfall feature, Early Park Admission, and a convenient shuttle to the parks. Preferred on-site status without the Express Unlimited perk — a good value for guests who plan strategically.',
    history: 'Sapphire Falls opened August 16, 2016. As a "Preferred" hotel (not Premier), it offers Early Park Admission but not Universal Express Unlimited — positioning it as a more affordable on-site option.',
    trivia: [
      'Preferred status means Early Park Admission is included — that one hour head start on VelociCoaster and Hagrid\'s is significant',
      'Strong/Zero bar offers one of the best craft cocktail programs among Universal hotels',
      'The resort connects internally to Royal Pacific, creating a path to the Premier hotel amenities',
    ],
    proTips: [
      '⏰ Early Park Admission alone can save hours of waits on major rides — especially for VelociCoaster and Hagrid\'s',
      '🍸 Strong/Zero bar is genuinely excellent for cocktails — visit in the evening',
      '💰 Significantly cheaper than Premier hotels while still offering key on-site perks',
    ],
    specs: {
      opened: '2016',
      rooms: '1,000 rooms',
      pools: '1 main pool with waterfall',
      restaurants: '3 dining locations',
      transportation: 'Shuttle + Water taxi',
      tier: 'Preferred On-Site Hotel',
      keyPerk: 'Early Park Admission (no Express Unlimited)',
    },
    resources: [
      { label: '💧 Book Sapphire Falls', url: 'https://www.universalorlando.com/web/en/us/hotels/loews-sapphire-falls-resort' },
    ],
  },

  {
    id: 'cabana-bay',
    name: 'Universal\'s Cabana Bay Beach Resort',
    shortName: 'Cabana Bay',
    emoji: '🏄',
    resort: 'universal-orlando',
    tier: 'Value',
    theme: '1950s–60s Florida beach resort',
    accentColor: '#f59e0b',
    priceRange: '$$',
    location: 'On-site Universal',
    transportation: ['Shuttle to parks', 'Walk to Epic Universe'],
    description: 'The most fun and affordable on-site Universal hotel — a retro 1950s/60s beach resort vibe with two massive pool complexes, bowling alley, and one extraordinary perk: it\'s within walking distance of Epic Universe.',
    history: 'Cabana Bay opened March 31, 2014 as Universal\'s first "Value" category on-site hotel. The resort is themed to Florida\'s retro beach culture of the 1950s and 60s — think vintage cars, neon signs, and poolside lounging.',
    trivia: [
      'Cabana Bay is the only Universal hotel currently within walking distance of Epic Universe',
      'Two separate pool complexes including a lazy river',
      'Galaxy Bowl — a vintage bowling alley — is one of the best hotel amenities at any Orlando resort',
      'Early Park Admission for Universal Studios, Islands of Adventure, and Epic Universe is included',
      'The resort has the largest pool area of any Universal hotel',
    ],
    proTips: [
      '✨ Walking distance to Epic Universe is the biggest strategic advantage of this hotel in 2025–2026',
      '🎳 Galaxy Bowl is genuinely fun — book lanes in advance especially on weekends',
      '🏊 The Lazy River pool complex is excellent — better than many more expensive hotels',
      '💰 Best value on-site Universal hotel, especially now that Epic Universe opened',
    ],
    specs: {
      opened: '2014',
      rooms: '2,200 rooms + suites',
      pools: '2 massive pool complexes including lazy river',
      restaurants: '2 dining locations + Galaxy Bowl',
      transportation: 'Shuttle to USF/IOA + Walk to Epic Universe',
      tier: 'Value On-Site Hotel',
      keyPerk: 'Early Park Admission to all 3 parks',
    },
    resources: [
      { label: '🏄 Book Cabana Bay', url: 'https://www.universalorlando.com/web/en/us/hotels/cabana-bay-beach-resort' },
    ],
  },

  {
    id: 'stella-nova',
    name: 'Universal\'s Stella Nova Resort',
    shortName: 'Stella Nova',
    emoji: '⭐',
    resort: 'universal-orlando',
    tier: 'Preferred',
    theme: 'Celestial / astronomy-inspired',
    accentColor: '#6d28d9',
    priceRange: '$$$',
    location: 'On-site Universal (Epic Universe area)',
    transportation: ['Walk to Epic Universe', 'Shuttle to USF/IOA'],
    description: 'One of two brand-new hotels opened alongside Epic Universe in 2025 — celestial-themed with star and constellation motifs, and walking distance to Epic Universe. Preferred status includes Early Park Admission.',
    history: 'Stella Nova Resort opened May 22, 2025 alongside Epic Universe, joining Terra Luna as Universal\'s newest hotel offerings positioned to serve the expanded Epic Universe area.',
    trivia: [
      'Opened May 22, 2025 — the same day as Epic Universe',
      'One of only two hotels within walking distance of Epic Universe at opening',
      'The celestial theming connects to the "Celestial Park" hub of Epic Universe',
      'Early Park Admission to Epic Universe is a major advantage during the park\'s high-demand opening period',
    ],
    proTips: [
      '✨ Walking distance to Epic Universe is essential during the high-demand 2025–2026 period',
      '⏰ Early Park Admission means riding Mario Kart and Battle at the Ministry before crowds',
      '🌟 The celestial lobby theming is one of the most striking hotel lobbies at Universal',
    ],
    specs: {
      opened: '2025',
      rooms: '750 rooms',
      pools: '2 pools',
      restaurants: '3 dining locations',
      transportation: 'Walk to Epic Universe + Shuttle to USF/IOA',
      tier: 'Preferred On-Site Hotel',
      keyPerk: 'Early Park Admission to all parks including Epic Universe',
    },
    resources: [
      { label: '⭐ Book Stella Nova', url: 'https://www.universalorlando.com/web/en/us/hotels/stella-nova-resort' },
    ],
  },

  {
    id: 'terra-luna',
    name: 'Universal\'s Terra Luna Resort',
    shortName: 'Terra Luna',
    emoji: '🌙',
    resort: 'universal-orlando',
    tier: 'Preferred',
    theme: 'Earth and moon / natural elements',
    accentColor: '#059669',
    priceRange: '$$$',
    location: 'On-site Universal (Epic Universe area)',
    transportation: ['Walk to Epic Universe', 'Shuttle to USF/IOA'],
    description: 'The companion resort to Stella Nova — earth and lunar themed, also opening with Epic Universe in 2025. Preferred status with Early Park Admission and walking distance to Epic Universe.',
    history: 'Terra Luna opened May 22, 2025 alongside Epic Universe and Stella Nova as part of Universal\'s massive expansion of on-site hotel capacity.',
    trivia: [
      'Opens simultaneously with Stella Nova and Epic Universe in May 2025',
      'Shares shuttle services with Stella Nova to the main Universal parks',
      'The earth and moon theming contrasts with Stella Nova\'s star/constellation motif',
    ],
    proTips: [
      '🌙 Book Terra Luna if Stella Nova is sold out — same Epic Universe walking access and perks',
      '⏰ Early Park Admission is especially valuable during Epic Universe\'s first year of operation',
    ],
    specs: {
      opened: '2025',
      rooms: '750 rooms',
      pools: '2 pools',
      restaurants: '3 dining locations',
      transportation: 'Walk to Epic Universe + Shuttle to USF/IOA',
      tier: 'Preferred On-Site Hotel',
      keyPerk: 'Early Park Admission to all parks including Epic Universe',
    },
    resources: [
      { label: '🌙 Book Terra Luna', url: 'https://www.universalorlando.com/web/en/us/hotels/terra-luna-resort' },
    ],
  },


  // ══════════════════════════════════════════════════════════
  // DISNEYLAND RESORT
  // ══════════════════════════════════════════════════════════
  {
    id: 'grand-californian',
    name: "Disney's Grand Californian Hotel & Spa",
    shortName: 'Grand Californian',
    emoji: '🌲',
    resort: 'disneyland',
    tier: 'Deluxe',
    theme: 'Arts & Crafts movement lodge',
    accentColor: '#92400e',
    priceRange: '$$$$$',
    location: 'Downtown Disney / DCA',
    transportation: ['Walk to Disney California Adventure (private entrance)', 'Walk to Disneyland Park', 'Walk to Downtown Disney'],
    description: 'The crown jewel of the Disneyland Resort — a stunning Arts and Crafts-style lodge that rivals the great national park hotels. The only hotel with its own gate directly into Disney California Adventure.',
    history: 'The Grand Californian opened on February 6, 2001 alongside Disney California Adventure. Designed by Peter Dominick, the hotel draws inspiration from the Arts and Crafts movement of the early 20th century — think Ahwahnee Hotel in Yosemite and the old Craftsman bungalows of Pasadena.',
    trivia: [
      'The hotel has its own private gate directly into Disney California Adventure — only guests of the Grand Californian can use it',
      'The lobby fireplace is 18 feet tall and the centerpiece of one of the most stunning hotel lobbies in California',
      'Napa Rose is considered one of the finest restaurants in the entire Disneyland Resort',
      'The hotel connects directly to Downtown Disney and is within a 5-minute walk of both parks',
    ],
    proTips: [
      '🚪 The private DCA entrance is the Grand Californian's killer feature — skip the main park entrance entirely',
      '🌅 The lobby is open to all guests — worth visiting even if you're not staying here',
      '🍷 Napa Rose requires reservations 60 days in advance — book immediately after reserving the room',
    ],
    specs: { opened: '2001', rooms: '948 rooms', pools: '3 pools', restaurants: '4 dining locations', tier: 'Deluxe Resort' },
    resources: [{ label: '🌲 Book Grand Californian', url: 'https://disneyland.disney.go.com/hotels/grand-californian-hotel/' }],
  },
  {
    id: 'disneyland-hotel',
    name: 'Disneyland Hotel',
    shortName: 'Disneyland Hotel',
    emoji: '🌟',
    resort: 'disneyland',
    tier: 'Deluxe',
    theme: 'Classic Disneyland nostalgia',
    accentColor: '#1a6fd4',
    priceRange: '$$$$',
    location: 'Downtown Disney Area',
    transportation: ['Walk to Disneyland Park via Downtown Disney', 'Walk to Downtown Disney', 'Monorail access nearby'],
    description: 'The original Disneyland hotel — open since 1955, the year Disneyland itself opened. Deeply nostalgic, with artifacts from Disneyland's history throughout and the closest hotel connection to the original Magic Kingdom.',
    history: 'The Disneyland Hotel opened in 1955 alongside the park itself, operated initially by Jack Wrather under a long-term Disney licensing agreement. Disney acquired it in 1988. The hotel underwent a major renovation completed in 2021, modernizing the rooms while maintaining vintage Disney character.',
    trivia: [
      'The hotel opened the same year as Disneyland — 1955',
      'The hotel is famous for its swimming pools themed to the Monorail — guests can swim through Monorail tracks',
      'The Sleeping Beauty Castle-shaped headboards in the Fantasy Tower are beloved by guests',
      'Disney acquired the hotel from the Wrather Corporation in 1988',
    ],
    proTips: [
      '🏊 The Monorail pool area is worth the stay for families — kids love swimming under the Monorail track',
      '📸 The lobby contains genuine artifacts and vintage Disney memorabilia',
    ],
    specs: { opened: '1955', rooms: '973 rooms', pools: '2 pools', tier: 'Deluxe Resort' },
    resources: [{ label: '🌟 Book Disneyland Hotel', url: 'https://disneyland.disney.go.com/hotels/disneyland-hotel/' }],
  },
  {
    id: 'pixar-place-hotel',
    name: 'Pixar Place Hotel',
    shortName: 'Pixar Place Hotel',
    emoji: '🎨',
    resort: 'disneyland',
    tier: 'Moderate',
    theme: 'Pixar Animation Studios',
    accentColor: '#7c3aed',
    priceRange: '$$$',
    location: 'Downtown Disney Area',
    transportation: ['Walk to Disneyland Park', 'Walk to Downtown Disney'],
    description: 'The reimagined former Paradise Pier Hotel — now themed to Pixar Animation Studios. The most affordable Disney-owned hotel at the Disneyland Resort with the same proximity benefits.',
    history: 'Formerly Paradise Pier Hotel, which opened in 1984. Rethemed to Pixar Place Hotel in 2024, featuring Pixar film character theming throughout.',
    trivia: [
      'Rethemed from Paradise Pier Hotel to Pixar Place Hotel in 2024',
      'Shares the same proximity to the parks as the Disneyland Hotel — less than 10 minutes walking',
      'The most affordable of the three official Disney hotels at the resort',
    ],
    proTips: [
      '💰 Best value among Disney-owned Disneyland Resort hotels',
      '🚶 Same walking distance to parks as the Disneyland Hotel at lower cost',
    ],
    specs: { opened: '1984', rooms: '481 rooms', tier: 'Moderate Resort' },
    resources: [{ label: '🎨 Book Pixar Place Hotel', url: 'https://disneyland.disney.go.com/hotels/pixar-place-hotel/' }],
  },

  // ══════════════════════════════════════════════════════════
  // UNIVERSAL STUDIOS HOLLYWOOD
  // ══════════════════════════════════════════════════════════
  {
    id: 'sheraton-universal',
    name: 'Sheraton Universal Hotel',
    shortName: 'Sheraton Universal',
    emoji: '🏨',
    resort: 'universal-hollywood',
    tier: 'Preferred',
    theme: 'Contemporary Hollywood',
    accentColor: '#0891b2',
    priceRange: '$$$',
    location: 'Adjacent to Universal Studios Hollywood',
    transportation: ['Walk to Universal Studios Hollywood (10 min)', 'Free shuttle to park entrance'],
    description: 'The closest full-service hotel to Universal Studios Hollywood — a Marriott-branded property adjacent to the park with shuttle service to the entrance and easy freeway access.',
    history: 'The Sheraton Universal has operated adjacent to the Universal Studios Hollywood complex for decades, serving as the primary hotel option for park visitors.',
    trivia: [
      'The hotel sits on the Universal Studios lot itself — literally adjacent to the working film studio',
      'Free shuttle service runs to the park entrance',
      'Many film industry professionals stay here while working on productions at the nearby soundstages',
    ],
    proTips: [
      '🚌 The free shuttle is faster than walking — use it especially in summer heat',
      '🎬 Ask at the front desk about any celebrity sightings — the hotel is popular with production crews',
    ],
    specs: { opened: '1969', rooms: '462 rooms', pools: '1 pool', tier: 'Adjacent Hotel', keyPerk: 'Free shuttle + closest hotel' },
    resources: [{ label: '🏨 Book Sheraton Universal', url: 'https://www.marriott.com/hotels/travel/laxus-sheraton-universal-hotel/' }],
  },
  {
    id: 'hilton-universal',
    name: 'Hilton Los Angeles/Universal City',
    shortName: 'Hilton Universal City',
    emoji: '🌆',
    resort: 'universal-hollywood',
    tier: 'Preferred',
    theme: 'Modern Hollywood',
    accentColor: '#1d4ed8',
    priceRange: '$$$',
    location: 'Universal City (adjacent)',
    transportation: ['Walk to Universal Studios Hollywood (5 min)', 'Adjacent to CityWalk'],
    description: 'A large Hilton property directly adjacent to Universal CityWalk and Universal Studios Hollywood — one of the most convenient hotel locations in Los Angeles.',
    history: 'Long-standing hotel property in Universal City, benefiting from its prime location adjacent to the entertainment complex.',
    trivia: [
      'Direct walking connection to CityWalk — no shuttle needed',
      'One of the closest hotel options to Universal Studios Hollywood',
      'Rooftop pool with views of the Hollywood Hills',
    ],
    proTips: [
      '🚶 The walking connection to CityWalk is the key advantage — skip the shuttle entirely',
      '🌆 Request a Hollywood Hills view room for a spectacular LA backdrop',
    ],
    specs: { rooms: '495 rooms', pools: '1 rooftop pool', tier: 'Adjacent Hotel' },
    resources: [{ label: '🌆 Book Hilton Universal City', url: 'https://www.hilton.com/en/hotels/laxuhhh-hilton-los-angeles-universal-city/' }],
  },

]

// Helper to get hotel by ID
export function getHotelById(id) {
  return HOTELS.find(h => h.id === id) || null
}

// Get hotels for a resort
export function getHotelsByResort(resortId) {
  return HOTELS.filter(h => h.resort === resortId)
}
